server:
  port: 8080



spring:
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    view:
      suffix: .html
      prefix: /
    pathmatch:
      #??io.springfox?swagger???????
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 4096MB
      file-size-threshold: 4096MB
      max-request-size: 4096MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    rewriteBatchedStatements=true ?mybatis???????????
    url: jdbc:mysql://localhost/bilibili?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 12345678
# mybatis-plus??
mybatis-plus:
  # xml??????????????????? Mapper ???? XML ?????
  mapper-locations: classpath*:mapper/*Mapper.xml
  # ?????????,?????
  global-config:
    db-config:
      #???? AUTO:"???ID??" INPUT:"????ID",ID_WORKER:"????ID (??????ID)", UUID:"????ID UUID";
      id-type: ASSIGN_ID
  configuration:
    # ??????????????:???????Java???????????
    map-underscore-to-camel-case: true
    # ??map?true:?????????????null,false:??????????????????
    call-setters-on-nulls: true
    # ?????????sql?????????????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true

Minio:
  host: "192.168.123.52"
#  host: "192.168.43.175"
  port: "9000"
  access_key: "AKIAIOSFODNN7EXAMPLE"
  secret_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

Mysql:
  url: jdbc:mysql://localhost/bilibili?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&rewriteBatchedStatements=true
  mysql_user: "root"
  mysql_password: "12345678"